version: '2'

services:
  monitor:
    image: 977933106931.dkr.ecr.us-west-1.amazonaws.com/dashbase/table
    cpu_shares: 512
    mem_limit: 4g
    ports:
      - "9888:9888"
      - "9988:9988"
    volumes:
      - /home/ec2-user/logs:/app/ecs-configurations/dashbase-tables/_system/logs:rw
      - /home/ec2-user/logs:/root/.dashbase/logs:rw
      - /home/ec2-user/index:/data/index:rw
    env_file:
      - saas_kafka_config.env
    environment:
      - ZOOKEEPER_URL=10.0.0.124:2181
      - LOG=/root/.dashbase/logs/debug.log
      - COMMAND=sleep 10s && dashbase-cli template download ecs-configurations --path /app/ dashbase-cli && --no-verify --distribution release service start table -p 9888 -ap 9988 -r 0 -c /app/ecs-configurations/dashbase-tables/_system/conf/config.yml saas-_system-0
  table:
    image: 977933106931.dkr.ecr.us-west-1.amazonaws.com/dashbase/table
    cpu_shares: 2048
    mem_limit: 8g
    links:
      - monitor
    volumes:
      - /home/ec2-user/logs:/app/ecs-configurations/dashbase-tables/filebeat/logs:rw
      - /home/ec2-user/logs:/root/.dashbase/logs:rw
      - /home/ec2-user/index:/data/index:rw
    env_file:
      - saas_kafka_config.env
    environment:
      - LOCAL_MONITOR_URL=monitor:9888
      - ZOOKEEPER_URL=10.0.0.124:2181
      - LOG=/root/.dashbase/logs/debug.log
      - COMMAND=sleep 10s && dashbase-cli template download ecs-configurations --path /app/ && dashbase-cli --no-verify --distribution release service start table -p 7889 -ap 7989 -r 0 -c /app/ecs-configurations/dashbase-tables/filebeat/conf/config.yml saas-table-0
  api:
    image: 977933106931.dkr.ecr.us-west-1.amazonaws.com/dashbase/api
    cpu_shares: 512
    mem_limit: 1g
    links:
      - monitor
    ports:
      - "9876:9876"
      - "9976:9976"
    volumes:
      - /home/ec2-user/logs:/app/ecs-configurations/dashbase-api/logs:rw
      - /home/ec2-user/logs:/root/.dashbase/logs:rw
    links:
      - table
    env_file:
      - saas_kafka_config.env
    environment:
      - LOCAL_MONITOR_URL=monitor:9888
      - ZOOKEEPER_URL=10.0.0.124:2181
      - LOG=/root/.dashbase/logs/debug.log
      - COMMAND=sleep 10s && dashbase-cli template download ecs-configurations --path /app/ && dashbase-cli --no-verify --distribution release service start api -p 9876 -ap 9976 -c /app/ecs-configurations/dashbase-api/conf/config.yml saas-api
  web:
    image: 977933106931.dkr.ecr.us-west-1.amazonaws.com/dashbase/web
    cpu_shares: 512
    mem_limit: 512m
    ports:
      - "8080:8080"
      - "8180:8180"
    volumes:
      - /home/ec2-user/logs:/root/.dashbase/logs:rw
    links:
      - api
    environment:
      - LOCAL_MONITOR_URL=monitor:9888
      - API_PORT=9876
      - API_HOST=api
      - LOG=/root/.dashbase/logs/debug.log
      - COMMAND=sleep 15s && dashbase-cli template download ecs-configurations --path /app/ && dashbase-cli --no-verify --distribution release service start web -p 8080 -ap 8180 -c /app/ecs-configurations/dashbase-web/conf/config.yml saas-web

  raven:
    image: 977933106931.dkr.ecr.us-west-1.amazonaws.com/dashbase/three-eyed-raven
    cpu_shares: 512
    mem_limit: 2g
    ports:
      - "12445:12445"
      - "12545:12545"
    volumes:
      - /home/ec2-user/logs/:/root/.dashbase/logs/:rw
    env_file:
      - saas_kafka_config.env
    environment:
      - PORT=12445
      - ADMINPORT=12545
    command: java -cp data-pipeline-1.0.0-SNAPSHOT.jar io.dashbase.ter.WargKafkaStreamsApplication server conf/saas-kafka-config.yml
