cluster:
  name: dashbase-api
  url: ${ZOOKEEPER_URL}
server:
  applicationConnectors:
    - type: http
      port: ${PORT}
  applicationContextPath: /
  adminContextPath: /admin
  adminConnectors:
      - type: http
        port: ${ADMINPORT}
metrics:
  reporters:
    - type: dashbase
      url: ${MONITOR_URL}
      meta:
        name: dashbase-staging
        type: dashbase-api
      includes:
        - ^jvm.*$
        - ^dashbase.*$
      useRegexFilters: true
      frequency: 5 seconds
logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: ../logs/dashbase-api.log
        archive: true
        archivedLogFilenamePattern: ../logs/dashbase-api-%d.log
        archivedFileCount: 9
        timeZone: UTC
      - type: dashbase
        url: ${MONITOR_URL}
        meta:
          name: dashbase-staging
          type: dashbase-api
        timeZone: UTC
