server:
  applicationConnectors:
    - type: http
      port: ${PORT}
  applicationContextPath: /
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: ${ADMINPORT}

website:
  cdn: "https://cdn.domain.com"
  domain: "https://www.domain.com"
  name: "Dashbase Web"

backend:
  host: ${API_HOST}
  port: ${API_PORT}

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: ../logs/dashbase-web.log
        archive: true
        archivedLogFilenamePattern: ../logs/dashbase-web-%d.log
        archivedFileCount: 9
        timeZone: UTC
